import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { ADD_TASK_MUTATION, DELETE_TASK_MUTATION } from "@/graphql/mutations";
import { GET_TASKS_QUERY } from "@/graphql/queries";
import { useMutation, useQuery } from "@apollo/client";
import { useToast } from "@chakra-ui/react";
// Components
import TaskForm from "@/components/TaskForm";
import TaskList from "@/components/TaskList";

export default function Home() {
  const [addTask] = useMutation(ADD_TASK_MUTATION);
  const [deleteTask] = useMutation(DELETE_TASK_MUTATION);
  const { loading, error, data } = useQuery(GET_TASKS_QUERY);

  const toast = useToast();

  if (error) {
    toast({
      title: "Error",
      description: "Task cannot be empty",
      status: "error",
      duration: 3000,
      isClosable: true,
    });
  }

  const handleAddTask = (task: string) => {
    addTask({
      variables: { task },
      refetchQueries: [{ query: GET_TASKS_QUERY }],
    });
  };

  const handleDeleteTask = (taskId: string) => {
    deleteTask({
      variables: { id: taskId },
      refetchQueries: [{ query: GET_TASKS_QUERY }],
    });
  };

  if (loading) {
    return <div>Loading tasks...</div>;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <TaskList tasks={data.tasks} onDeleteTask={handleDeleteTask} />
        <TaskForm onAddTask={handleAddTask} />
      </main>
    </>
  );
}
